services:
  - type: web
    name: novabot-readonly-dashboard
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_NAME
        value: NovaBot
      - key: PREFIX
        value: .
      - key: PORT
        value: 10000
      - key: AUTO_CONNECT
        value: false
