require("dotenv").config();
const express=require("express"),http=require("http"),path=require("path"),fs=require("fs");
const QRCode=require("qrcode"),terminal=require("qrcode-terminal"),{Server}=require("socket.io");
const OpenAI=require("openai"); const {Client,LocalAuth}=require("whatsapp-web.js");
const PORT=Number(process.env.PORT||10000), PREFIX=process.env.PREFIX||".";
const BOT=process.env.BOT_NAME||"NovaBot", OWNER=(process.env.OWNER_NUMBER||"").replace(/\D/g,"");
const AUTH=process.env.AUTH_PATH||path.join(process.cwd(),".wwebjs_auth");
const DATA=process.env.DATA_PATH||path.join(process.cwd(),"data"), TOKEN=process.env.DASHBOARD_TOKEN||"";
fs.mkdirSync(DATA,{recursive:true});
const app=express(),server=http.createServer(app),io=new Server(server);
let state="starting",readyAt=null,qr=null,pairingCode=null; const chats=new Map(),messages=new Map(),history=new Map();
const client=new Client({authStrategy:new LocalAuth({clientId:"novabot",dataPath:AUTH}),puppeteer:{headless:true,executablePath:process.env.PUPPETEER_EXECUTABLE_PATH,args:["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage","--disable-gpu","--no-first-run","--no-zygote"]}});
const ok=req=>!TOKEN||req.query.token===TOKEN||req.headers["x-dashboard-token"]===TOKEN;
const text=(x,n=4000)=>typeof x==="string"?x.slice(0,n):"";
function remember(m){const id=m.id?._serialized||m.id?.id||String(Date.now()+Math.random()),x={id,chatId:m.from||m.to,fromMe:!!m.fromMe,author:m.author||null,body:text(m.body),type:m.type||"chat",timestamp:Number(m.timestamp||Date.now()/1000)*1000,hasMedia:!!m.hasMedia,isGroup:(m.from||m.to||"").endsWith("@g.us")};messages.set(id,x);if(messages.size>5000)messages.delete(messages.keys().next().value);io.emit("message:new",x)}
async function rememberChat(c){const id=c.id?._serialized;if(!id)return;let name=c.name||c.pushname||c.formattedTitle||id;const x={id,name:text(name,200),isGroup:!!c.isGroup,unreadCount:Number(c.unreadCount||0),timestamp:Number(c.timestamp||0)*1000||Date.now()};chats.set(id,x);io.emit("chat:update",x)}
const help=()=>`*${BOT}*\n\nGeneral: .help .menu .ping .alive .owner .about .time .echo .whoami\nGames: .games .rps rock .dice .coin .8ball question .guess\nFun: .joke .quote .choose a|b|c .truth .dare .calc 12*8\nGroups: .groupinfo .admins .tagall .everyone .hidetag .link\nMedia: reply to media with .sticker\nAI: .ai question .resetai`;
async function ai(chat,prompt){if(process.env.AI_ENABLED!=="true"||!process.env.OPENAI_API_KEY)return "AI is disabled on this server.";const o=new OpenAI({apiKey:process.env.OPENAI_API_KEY}),h=history.get(chat)||[];h.push({role:"user",content:prompt});const r=await o.responses.create({model:process.env.OPENAI_MODEL||"gpt-5.6-luna",instructions:`You are ${BOT}, a concise friendly WhatsApp bot.`,input:h.slice(-10)});const a=r.output_text||"No response.";h.push({role:"assistant",content:a});history.set(chat,h.slice(-10));return a}
async function admin(m){try{const c=await m.getChat(),p=c.participants.find(x=>x.id._serialized===m.author);return !!(p?.isAdmin||p?.isSuperAdmin)}catch{return false}}
async function command(m){const b=(m.body||"").trim(),parts=b.slice(PREFIX.length).trim().split(/\s+/),c=(parts.shift()||"").toLowerCase(),a=parts.join(" ");
if(!b.startsWith(PREFIX))return;
if(["help","menu"].includes(c))return m.reply(help());
if(c==="ping")return m.reply("pong 🏓"); if(c==="alive")return m.reply(`🟢 ${BOT} is alive.`);
if(c==="about")return m.reply(`${BOT} — personal WhatsApp Web experiment.`);
if(c==="time")return m.reply(new Date().toLocaleString()); if(c==="echo")return m.reply(a||"Nothing to echo.");
if(c==="owner")return m.reply(OWNER?`Owner: https://wa.me/${OWNER}`:"Owner not configured.");
if(c==="whoami")return m.reply(`Chat: ${m.from}`);
if(c==="games")return m.reply("🎮 .rps rock|paper|scissors\n.dice\n.coin\n.8ball question\n.guess");
if(c==="rps"){let u=(parts[0]||"").toLowerCase(),v=["rock","paper","scissors"];if(!v.includes(u))return m.reply("Use .rps rock|paper|scissors");let x=v[Math.floor(Math.random()*3)],w=(u==="rock"&&x==="scissors")||(u==="paper"&&x==="rock")||(u==="scissors"&&x==="paper");return m.reply(`You: ${u}\nMe: ${x}\n${u===x?"🤝 Draw!":w?"🎉 You win!":"😈 I win!"}`)}
if(c==="dice")return m.reply(`🎲 ${1+Math.floor(Math.random()*6)}`);if(c==="coin")return m.reply(Math.random()<.5?"🪙 Heads!":"🪙 Tails!");
if(c==="8ball"){if(!a)return m.reply("Use .8ball Will I win?");return m.reply("🎱 "+["Yes.","No.","Definitely.","Probably.","Ask again later.","Very doubtful."][Math.floor(Math.random()*6)])}
if(c==="guess")return m.reply("🎯 I'm thinking of a number from 1–10. Try guessing!");
if(c==="joke")return m.reply(["Why did the computer get cold? It left its Windows open. 😂","Why do programmers prefer dark mode? Because light attracts bugs. 🐛"][Math.floor(Math.random()*2)]);
if(c==="quote")return m.reply(["The secret of getting ahead is getting started.","Simplicity is the soul of efficiency."][Math.floor(Math.random()*2)]);
if(c==="choose"){let v=a.split("|").map(x=>x.trim()).filter(Boolean);return m.reply(v.length>1?`🤔 ${v[Math.floor(Math.random()*v.length)]}`:"Use .choose a|b|c")}
if(c==="truth"||c==="dare")return m.reply(c==="truth"?"🫣 Truth: What's a goal you're working toward?":"😈 Dare: Send the next message using only emojis.");
if(c==="calc"){if(!/^[0-9+\-*/().%\s]+$/.test(a))return m.reply("Only basic arithmetic is allowed.");try{return m.reply(`🧮 ${a} = ${Function('"use strict";return ('+a+')')()}`)}catch{return m.reply("Couldn't calculate that.")}}
if(c==="ai")return m.reply(await ai(m.from,a||"Say hello."));if(c==="resetai"){history.delete(m.from);return m.reply("🧠 AI history reset.")}
if(c==="sticker"){if(!m.hasMedia)return m.reply("Reply to media with .sticker");try{let media=await m.downloadMedia();return m.reply(media,undefined,{sendMediaAsSticker:true})}catch{return m.reply("Sticker conversion failed.")}}
if(["groupinfo","admins","tagall","everyone","hidetag","link"].includes(c)&&!m.from.endsWith("@g.us"))return m.reply("This command is for groups.");
if(c==="groupinfo"){let g=await m.getChat();return m.reply(`👥 ${g.name}\nMembers: ${g.participants.length}`)}
if(c==="admins"){let g=await m.getChat(),p=g.participants.filter(x=>x.isAdmin||x.isSuperAdmin);return m.reply("👑 "+p.map(x=>"@"+x.id.user).join(" "),undefined,{mentions:p.map(x=>x.id._serialized)})}
if(["tagall","everyone","hidetag"].includes(c)){if(!(await admin(m)))return m.reply("Admin-only command.");let g=await m.getChat(),ids=g.participants.map(x=>x.id._serialized),body=c==="hidetag"?(a||"👀"):`${a||"📢 Everyone"}\n\n${g.participants.map(x=>"@"+x.id.user).join(" ")}`;return m.reply(body,undefined,{mentions:ids})}
if(c==="link"){if(!(await admin(m)))return m.reply("Admin-only command.");try{return m.reply("🔗 https://chat.whatsapp.com/"+await (await m.getChat()).getInviteCode())}catch{return m.reply("Couldn't get invite link.")}}}
client.on("qr",async q=>{state="qr";pairingCode=null;qr=await QRCode.toDataURL(q);terminal.generate(q,{small:true});io.emit("status",{state,qr})});
client.on("code",code=>{pairingCode=code;qr=null;state="pairing_code";console.log(`${BOT} pairing code: ${code}`);io.emit("pairing:code",{code});io.emit("status",{state})});
client.on("authenticated",()=>{state="authenticated";qr=null;pairingCode=null;io.emit("status",{state})});
client.on("ready",()=>{state="ready";readyAt=new Date().toISOString();qr=null;pairingCode=null;console.log(`${BOT} ready`);io.emit("status",{state,readyAt})});
client.on("auth_failure",e=>{state="auth_failure";console.error(e);io.emit("status",{state})});
client.on("disconnected",e=>{state="disconnected";console.log(e);io.emit("status",{state})});
client.on("message",async m=>{remember(m);try{await rememberChat(await m.getChat())}catch{}try{if((m.body||"").trim().toLowerCase().match(/^(hi|hello|hey)$/))return m.reply(`Hey 👋 I'm ${BOT}. Try ${PREFIX}menu`);await command(m)}catch(e){console.error(e)}});
client.on("message_create",m=>remember(m));
app.get("/health",(q,s)=>s.json({ok:true,bot:BOT,whatsapp:state,readyAt,dashboard:"read-only"}));
app.get("/",(q,s)=>{if(!ok(q))return s.status(401).send("<h2>Unauthorized</h2>");s.send(connectionHtml())});
app.get("/qr",(q,s)=>{if(!ok(q))return s.status(401).send("<h2>Unauthorized</h2>");s.send(connectionHtml())});
app.get("/api/connection",(q,s)=>{if(!ok(q))return s.status(401).json({error:"Unauthorized"});s.json({bot:BOT,state,readyAt,hasQr:!!qr,pairingCode})});
app.post("/api/pair",express.json(),async(q,s)=>{if(!ok(q))return s.status(401).json({error:"Unauthorized"});const phone=String(q.body?.phone||"").replace(/\D/g,"");if(!/^\d{7,15}$/.test(phone))return s.status(400).json({error:"Enter your WhatsApp number with country code, numbers only. Example: 2348012345678"});if(state==="ready")return s.status(409).json({error:"Bot is already connected."});try{const code=await client.requestPairingCode(phone,true,180000);pairingCode=code;qr=null;state="pairing_code";io.emit("pairing:code",{code});io.emit("status",{state});return s.json({ok:true,code})}catch(e){console.error(e);return s.status(500).json({error:e?.message||"Could not generate pairing code."})}});
app.post("/api/pair/cancel",async(q,s)=>{if(!ok(q))return s.status(401).json({error:"Unauthorized"});try{await client.cancelPairingCode();pairingCode=null;state="qr";io.emit("status",{state});return s.json({ok:true})}catch(e){return s.status(500).json({error:e?.message||"Could not switch to QR mode."})}});
app.get("/api/bootstrap",async(q,s)=>{if(!ok(q))return s.status(401).json({error:"Unauthorized"});if(state==="ready")try{for(const c of (await client.getChats()).slice(0,300))await rememberChat(c)}catch{}s.json({bot:BOT,whatsapp:state,readyAt,readOnly:true,chats:[...chats.values()],messages:[...messages.values()].slice(-1000)})});
const connectionHtml=()=>`<!doctype html><html><head><meta name="viewport" content="width=device-width"><title>${BOT} Connection</title><style>*{box-sizing:border-box}body{margin:0;background:#08111f;color:#eaf1fb;font:15px system-ui;min-height:100vh;display:grid;place-items:center}.wrap{width:min(900px,94vw)}.card{background:#101b2c;border:1px solid #2b3b55;border-radius:20px;padding:28px;box-shadow:0 20px 70px #0006}.head{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:22px}.brand{font-size:23px;font-weight:800}.muted{color:#91a3bd}.status{padding:8px 12px;border-radius:999px;background:#18263b}.tabs{display:flex;gap:8px;margin-bottom:20px}.tab{border:1px solid #30425f;background:#142239;color:#dce7f6;padding:10px 14px;border-radius:10px;cursor:pointer}.tab.active{background:#1d3555}.panels{display:grid;grid-template-columns:1fr 1fr;gap:22px}.panel{border:1px solid #293b57;border-radius:16px;padding:22px;text-align:center}.qr{width:280px;height:280px;max-width:100%;background:#fff;border-radius:12px;object-fit:contain;padding:8px}.code{font-size:32px;letter-spacing:6px;font-weight:800;background:#0a1423;border:1px dashed #3b5273;padding:20px 10px;border-radius:12px;margin:28px 0}.input{width:100%;padding:13px;border-radius:10px;border:1px solid #3b4d69;background:#0b1627;color:#fff;font-size:16px}.btn{width:100%;padding:13px;border:0;border-radius:10px;background:#2a6df4;color:white;font-weight:700;cursor:pointer;margin-top:10px}.btn.secondary{background:#24354e}.msg{min-height:22px;margin-top:12px;color:#9fb2cd}.links{margin-top:22px;display:flex;justify-content:space-between}.links a{color:#8bb7ff;text-decoration:none}@media(max-width:700px){.panels{grid-template-columns:1fr}.card{padding:18px}.qr{width:240px;height:240px}}
</style></head><body><div class="wrap"><div class="card"><div class="head"><div><div class="brand">🔗 ${BOT} Connection</div><div class="muted">Connect this bot to your WhatsApp account.</div></div><div id="status" class="status">Connecting…</div></div><div class="tabs"><button id="qrTab" class="tab active">QR code</button><button id="codeTab" class="tab">Pairing code</button></div><div class="panels"><section id="qrPanel" class="panel"><h2>Scan QR code</h2><p class="muted">WhatsApp → Settings → Linked devices → Link a device</p><div id="qrBox"><p class="muted">Waiting for QR…</p></div><button class="btn secondary" id="refresh">Refresh status</button></section><section id="codePanel" class="panel"><h2>Use pairing code</h2><p class="muted">Enter your WhatsApp number with country code.</p><input id="phone" class="input" inputmode="numeric" placeholder="2348012345678"><button class="btn" id="pair">Get pairing code</button><div id="code" class="code">—</div><div id="msg" class="msg"></div><button class="btn secondary" id="cancel">Switch back to QR</button></section></div><div class="links"><a href="/dashboard${location.search}">Open read-only dashboard →</a><span class="muted">One WhatsApp connection</span></div></div></div><script>
const token=new URLSearchParams(location.search).get("token")||"", qs=token?"?token="+encodeURIComponent(token):"";const $=x=>document.getElementById(x);function st(x){$('status').textContent=x==='ready'?'🟢 Connected':x==='pairing_code'?'🔵 Pairing code':x==='qr'?'🟡 Waiting for QR':'🟡 '+x}function render(d){st(d.state);$('qrBox').innerHTML=d.hasQr?'<img class="qr" src="/qr-image'+qs+'">':'<p class="muted">No QR active. Use pairing code or wait for the connection screen to update.</p>';$('code').textContent=d.pairingCode||'—'}async function load(){const r=await fetch('/api/connection'+qs);if(r.ok)render(await r.json());else $('status').textContent='🔴 Unauthorized'}load();setInterval(load,2500);$('qrTab').onclick=()=>{$('qrTab').classList.add('active');$('codeTab').classList.remove('active')};$('codeTab').onclick=()=>{$('codeTab').classList.add('active');$('qrTab').classList.remove('active')};$('pair').onclick=async()=>{ $('msg').textContent='Generating code…';const r=await fetch('/api/pair'+qs,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:$('phone').value})});const d=await r.json();$('msg').textContent=d.error||'Enter this code in WhatsApp on your phone.';if(d.code)$('code').textContent=d.code;load()};$('cancel').onclick=async()=>{await fetch('/api/pair/cancel'+qs,{method:'POST'});load()};$('refresh').onclick=load;const sio=io();sio.on('status',load);sio.on('pairing:code',x=>{$('code').textContent=x.code;st('pairing_code')});
</script></body></html>`;
app.get("/qr-image",(q,s)=>{if(!ok(q)||!qr)return s.status(404).end();try{s.set("Content-Type","image/png");s.end(Buffer.from(qr.split(",")[1],"base64"))}catch{s.status(500).end()}});
const html=()=>`<!doctype html><html><head><meta name="viewport" content="width=device-width"><title>${BOT} Dashboard</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#e7edf7;font:14px system-ui}.top{height:62px;padding:0 18px;display:flex;justify-content:space-between;align-items:center;background:#101827;border-bottom:1px solid #29364c}.app{height:calc(100vh - 62px);display:grid;grid-template-columns:300px 1fr}.side{overflow:auto;border-right:1px solid #29364c}.search{padding:10px}.search input{width:100%;padding:10px;border-radius:9px;border:1px solid #33415a;background:#111c2d;color:#fff}.chat{padding:12px 15px;border-bottom:1px solid #1c293b;cursor:pointer}.chat:hover,.active{background:#172338}.main{display:flex;flex-direction:column}.bar{padding:13px 17px;border-bottom:1px solid #29364c}.notice{font-size:11px;color:#9fb0c7;margin-top:4px}.msgs{flex:1;overflow:auto;padding:18px;display:flex;flex-direction:column;gap:8px}.bubble{max-width:75%;padding:10px 13px;border-radius:14px;background:#172338;align-self:flex-start}.me{align-self:flex-end;background:#183029}.time{font-size:10px;color:#8fa0b8;margin-top:5px}.empty{margin:auto;color:#8493aa;text-align:center}@media(max-width:700px){.app{grid-template-columns:115px 1fr}.chat{padding:12px 7px}.bubble{max-width:90%}}</style></head><body>
<div class="top"><b>🤖 ${BOT} Dashboard</b><span id="status">Connecting…</span></div><div class="app"><aside class="side"><div class="search"><input id="search" placeholder="Search chats"></div><div id="chats"></div></aside><main class="main"><div class="bar"><b id="title">Select a chat</b><div class="notice">🔴 READ-ONLY — this page does not intentionally send WhatsApp actions.</div></div><div id="msgs" class="msgs"><div class="empty">Waiting…</div></div></main></div>
<script src="/socket.io/socket.io.js"></script><script>
const token=new URLSearchParams(location.search).get("token")||"",api="/api/bootstrap"+(token?"?token="+encodeURIComponent(token):"");let S={ch:new Map(),m:[],sel:null};
const $=x=>document.getElementById(x),esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function tm(t){return new Date(t).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}
function chats(){let q=$("search").value.toLowerCase(),a=[...S.ch.values()].filter(x=>(x.name||"").toLowerCase().includes(q)).sort((a,b)=>b.timestamp-a.timestamp);$("chats").innerHTML=a.map(c=>'<div class="chat '+(S.sel===c.id?'active':'')+'" data-id="'+esc(c.id)+'"><b>'+esc(c.name||c.id)+'</b><div class="time">'+(c.isGroup?'👥 Group':'Private')+' · '+(c.unreadCount||0)+' unread</div></div>').join("");document.querySelectorAll(".chat").forEach(x=>x.onclick=()=>{S.sel=x.dataset.id;$("title").textContent=S.ch.get(S.sel)?.name||S.sel;chats();msgs()})}
function msgs(){let a=S.m.filter(x=>x.chatId===S.sel).sort((a,b)=>a.timestamp-b.timestamp);$("msgs").innerHTML=a.length?a.map(m=>'<div class="bubble '+(m.fromMe?'me':'')+'">'+esc(m.body||'['+m.type+']')+'<div class="time">'+tm(m.timestamp)+(m.hasMedia?' · 📎':'')+'</div></div>').join(""): '<div class="empty">No cached messages for this chat yet.</div>';$("msgs").scrollTop=$("msgs").scrollHeight}
fetch(api).then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);$("status").textContent=d.whatsapp==="ready"?"🟢 Connected":"🟡 "+d.whatsapp;(d.chats||[]).forEach(x=>S.ch.set(x.id,x));S.m=d.messages||[];chats();msgs()}).catch(e=>$("status").textContent="🔴 "+e.message);
$("search").oninput=chats;const ioClient=io();ioClient.on("status",x=>$("status").textContent=x.state==="ready"?"🟢 Connected":"🟡 "+x.state);ioClient.on("chat:update",x=>{S.ch.set(x.id,x);chats()});ioClient.on("message:new",x=>{S.m.push(x);if(S.m.length>5000)S.m.shift();if(!S.ch.has(x.chatId))S.ch.set(x.chatId,{id:x.chatId,name:x.chatId,isGroup:x.isGroup,timestamp:x.timestamp});S.ch.get(x.chatId).timestamp=x.timestamp;chats();if(S.sel===x.chatId)msgs()});
</script></body></html>`;
app.get("/dashboard",(q,s)=>{if(!ok(q))return s.status(401).send("<h2>Unauthorized</h2>");s.send(html())});
server.listen(PORT,"0.0.0.0",()=>{console.log(`${BOT} listening on ${PORT}`);client.initialize()});
